spring:
  application:
    name: ButexBackend
  datasource:
    url: jdbc:postgresql://dpg-cs8lh8bv2p9s73e3ndtg-a:5432/butex
    username: butex
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

ButexValues:
  app:
    jwtSecret: ${JWT_SECRET}
    jwtExpirationMs: 86400000