spring:
  application:
    name: ButexBackend
  datasource:
  #    url: jdbc:postgresql://dpg-cs8lh8bv2p9s73e3ndtg-a.frankfurt-postgres.render.com:5432/butex
  #    username: butex
  #    password: ${DB_PASSWORD}
    url: jdbc:postgresql://localhost:5432/ButexDB
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update

furgonetka:
  environment-url: https://api.sandbox.furgonetka.pl
  api-token: ${FURGONETKA_API_TOKEN}
  endpoint:
    package-validate: /packages/validate
    package-create: /packages
paynow:
  environment-url: https://api.sandbox.paynow.pl
  api-token: ${PAYNOW_API_TOKEN}
  signature-token: ${PAYNOW_SIGNATURE_TOKEN}
  endpoint:
    payment-create: /v1/payments
    payment-status: /v1/payments/{paymentId}/status

ButexValues:
  app:
    jwtSecret: ${JWT_SECRET}
    jwtExpirationMs: 86400000